language: python

python:
  - 3.9

install:
  - pip install -r requirements.txt
  - pip install urllib3==1.26.6

before_script: 
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - black --check .
  - flake8 --max-line-length=92 .
  - coverage run manage.py test

after_script:
  - COVERALLS_REPO_TOKEN=xf6rncn6E2jwpdkuT9bD3hIyN4vScCZm6 coveralls

# deploy:
#   provider: elasticbeanstalk
#   access_key_id:
#     secure: "N2CazvXzWAMKYOycRk7gwfvaiHDsgswJVZ+8zttQO6YUrpT06UzGKXc96L2Q4wgSChMjujf0ideiV7O8Pl4JUiMv4kkaZEicCHrwkcOyydvfmHPtzvaOO8ZWu5Sh+rIXjh71Le9SWAyEUiHUVr3EMocN0t/6W+fGS68Ymv0ZqgX577oBpzfviz0kKxxoVkJpYk2kx0bmz90ouK3Jw3dQcQV0BBqg9bbDwN79g8vQwA+BaRqmlczCc/WWElLNfQ1FgI7madnbnuP75+2XKuebL9ywsHkgPqzwpdyrJRjxUKvfRAShwTNQ1ZUZBnmk1bM7dBmAN+8WXC0u0aNGPlcwXp5ZCGyDicrn4yMeZ5LiOVUSETYCESAirfZzMpGRgFoM+ozjTdRHnTTeCL90uZXlvamMmnbtwvXdmoEwiPrdM5XsD/TTkz38rRlVX6YpNg7oNw07O72akZP555mJ5dpkN6n0bbRZnAbJ5rOe0zQ6zz5bQneeicBjUKcTIdjGcKUpGYwtC9cSAK0vWxiXv5QKy7QMPIlSLBXuRWdhpbXk+puakEnP5OAdrI31kDD3AHm6QBnLA+Q9UrDjcipbj7j1V9OH49/SlXlq0ZHCyP40f2XIOk2rVuIalepWIO8LRQOhcegK1fkQGvRP3oTKRhiIHn+i4TSpJLemHCxo0aIgBZs="
#   secret_access_key:
#     secure: "kyBXkCwhPQaU02QeRtP3r3uFz8OvGgMl+cPwiGdIHiUk+C9ICO/z1pse2wwjfYph/ZklZLoYXV7nvXz9V63pNHB7DX/Pq5WporCSOpDgZzwIzOw47HtJbQimOQob9TOZo86+VINX6GuM5vgAxyrv3CJ+VAKbX71URN1q+bvXHFiBrWcOTHjN+9HNNg/CiqGAFMJ9AOW3kKkbcP/0EPGX06pIM6D1VnuCo13FBHrrxc2+ZgW8/+ShkRNT35nI5mMg015PMDl0hl1d3fiDjUBiCMQwFV8KvbQ9iqEKqw0jh6KViI2msTxAHF2NVtdDzrxkq76s/8J/23JPQdjPCjBKI1LZki7HHrG9ReOdcevRNLuIn7PRvOyTFa7wHj2jqCxGvy0S6pFcVeWKH2+7bUfsozpDS3H6fwhcpA+0i4HBc66wzPupWc/iF/lH3aKDekAjnN1BIaCND5EiQ1y0Q82r712UZgSYvxgC0/6DTapfoJ5pZqRkIqzXjoEj/+JlrjV2XCjsSgmn36QsEoGFUJLeDP480/XwHbgrT4qLnVnstJKgaY3seNcaXQqoGddWPa0IEHPBMBS1ABjYXUe4wrDmQ+9DbV6uPHCOYyhHY54zNrxDcKNeuUHWfWI6j2nePRiVGC1S6fmTYK4oH0D8yH/XZQOtmjWx5io11ADNe3WkNsM="
#   region: us-west-2
#   app: django-jw4186
#   env: jw4186-env
#   bucket_name: elasticbeanstalk-us-west-2-982534375021
#   on:
#      repo: jeffwong97/django-aws-app
#     branch: main
#   skip_cleanup: 'true'
